# The URL the site will be built for
base_url = "https://www.wyilio.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

build_search_index = true

title = "Wyilio"
description = "Wyilio's Blog"

default_language = "en"

generate_feeds = true
feed_filenames=["atom.xml", "rss.xml"]

taxonomies = [
    {name = "tags"}
]

[markdown]
render_emoji = false
smart_punctuation = false

[extra]
date_format="%e %B %Y"
menu_links = []
